{{
    config(
        materialized='incremental',
        schema=env_var('ENV_SCHEMA') + '_di',
        unique_key=['billingno'],
        group='pss_awo_sales',
        tags=['daily']
    )
}}

with sales as (
	select 
		* 
		,rank = row_number() over(partition by billingno order by coalesce(lastmodifiedtime, createdtime) desc)
	from {{ source(env_var('ENV_SCHEMA') + '_dl', 'awo_transaction_sales_tvc_pss_staging') }}
    {% if is_incremental() %}
    where coalesce(lastmodifiedtime, createdtime) >= '{{ var('min_date') }}'
        and coalesce(lastmodifiedtime, createdtime) <= '{{ var('max_date') }}'
    {% endif %}
)
,clean as (
	select  
		billingfuid
		,billingno
		,billingcreatedtime
		,choosenid
		,id
		,quotationid
		,salesorderfuid
		,tvcdataquotid
		,awapplicationtype
		,awccname
		,awcellphone
		,awemergencycontactaddr
		,awemergencycontactname
		,awemergencycontactphone
		,awemergencycontactrelation
		,awcustomerdata
		,awhomephone
		,awidtype
		,awidnumber
		,awisexpaab
		,awisexpm88
		,awisexpnontaff
		,awisexptafs
		,awkindoforder
		,awmemberno
		,awmothermaidenname
		,awofficerphone
		,awownername
		,awproductcode
		,awretailorfleet
		,awsalespurpose
		,awpurchasetype
		,bpkbno
		,bpkbowner
		,customerno
		,customersex
		,customertype
		,cpbirthdate
		,cpbirthplace
		,cpcellphone
		,cpemailaddr
		,cphomaddr
		,cphombupat
		,cphomcamat
		,cphomlurah
		,cphomphone
		,cphomprocy
		,cphomzipcd
		,cpidno
		,cpjobposition
		,cpname
		,cpofcphone
		,cprole
		,datamodel
		,dmbirthdate
		,dmbirthplace
		,dmcellphone
		,dmemailaddr
		,dmhomaddr
		,dmhombupat
		,dmhomcamat
		,dmhomlurah
		,dmhomphone
		,dmhomprocy
		,dmhomzipcd
		,dmidno
		,dmjobposition
		,dmname
		,dmofficephone
		,dmrole
		,dtb2baddr
		,dtb2bbupat
		,dtb2bcamat
		,dtb2bcmpname
		,dtb2blurah
		,dtb2bprocy
		,dtb2bzipcd
		,dtlegalidno
		,dtlegaddr
		,dtlegbupat
		,dtlegcamat
		,dtlegcmpname
		,dtleglurah
		,dtlegprocy
		,dtlegzipcd
		,dtdatefound
		,dtdeedno
		,dtdeeddate
		,dtnote
		,dtofcaddr
		,dtofcbupat
		,dtofccamat
		,dtofccmpname
		,dtofclurah
		,dtofcprocy
		,dtofczipcd
		,dtsubject
		,gnbusinessseg
		,gncorporatetype
		,gnindustryid
		,gniscp
		,gnnumofemp
		,gntotalrevenue
		,grbusaddr
		,grbusbupat
		,grbuscamat
		,grbuscmpname
		,grbuslurah
		,grbusprocy
		,grbuszipcd
		,grcustmodel
		,grdateofbirth
		,grhomaddr
		,grhombupat
		,grhomcamat
		,grhomlurah
		,grhomname
		,grhomprocy
		,grhomzipcd
		,gridtype
		,gridnumber
		,grjobposition
		,grlegaddr
		,grlegbupat
		,grlegcamat
		,grlegcmpname
		,grleglurah
		,grlegprocy
		,grlegzipcd
		,grname
		,grnpwp
		,grofcaddr
		,grofcbupat
		,grofccamat
		,grofccmpname
		,grofclurah
		,grofcprocy
		,grofczipcd
		,grphone
		,grreligion
		,grsex
		,incomprehensive
		,incurrencykode
		,incustomermodel
		,inestimationpolisdate
		,intotallossonly
		,inisconfirmpolicydate
		,iniscontactperson
		,inisearthquake
		,inisfloodcoverage
		,inisterrorismoption
		,inissrccoption
		,inispaoption
		,injwp
		,innumberofseat
		,inpadrvsuminsured
		,inpayer
		,inpapassinsured
		,inpolicefee
		,intotalprem
		,intplsuminsured
		,iscancelled
		,isfcrspcphomaddr
		,isfcrspdmhomaddr
		,isfcrspdtb2baddr
		,isfcrspdtlegaddr
		,isfcrspdtofcaddr
		,isfcrspgrbusaddr
		,isfcrspgrhomaddr
		,isfcrspgrlegaddr
		,isfcrspgrofcaddr
		,isfcrspprbusaddr
		,isfcrspprb2baddr
		,isfcrspprhomaddr
		,isfcrspprlegaddr
		,isfcrspprofcaddr
		,isfcrspspbusaddr
		,isfcrspsphomaddr
		,isfcrspsplegaddr
		,isfcrspspofcaddr
		,isfleet
		,isexistguarantor
		,ishassendtoxml
		,isretail
		,istotallostonly
		,isvalidforawo
		,isvalidforinsurance
		,isvalidfortso
		,isvalidfortafs
		,isvalidforinittafs
		,isvalidforinittso
		,inpurpose
		,jbbusinessid
		,jbcmpname1
		,jbcmpname2
		,jbindustryid
		,jbposition
		,jbtotalrevenue1
		,jbtotalrevenue2
		,jbworkfrom
		,jbtenure
		,jbnumofemp1
		,jbnumofemp2
		,jbnumofjobs
		,mnaccounttype
		,mncurrency
		,mnexpenditure
		,mngrossincome
		,mninstallment
		,mnothercredit
		,mnotherincome
		,prbusaddr
		,prbusbupat
		,prbuscamat
		,prbuscmpname
		,prbuslurah
		,prbusprocy
		,prbuszipcd
		,prb2baddr
		,prb2bbupat
		,prb2bcamat
		,prb2bcmpname
		,prb2blurah
		,prb2bprocy
		,prb2bzipcd
		,prcellphone
		,prdateofbirth
		,preducation
		,premailaddr
		,prhomaddr
		,prhombupat
		,prhomcamat
		,prhomlurah
		,prhomname
		,prhomphone
		,prhomprocy
		,prhomzipcd
		,pridnumber
		,pridtype
		,priscp
		,prisflagtaxinvoice
		,prlegaddr
		,prlegbupat
		,prlegcamat
		,prlegcmpname
		,prleglurah
		,prlegphone
		,prlegprocy
		,prlegzipcd
		,prlivingplacestatus
		,prmaritalstatus
		,prnationality
		,prnickname
		,prnumofdepndt
		,procupation
		,profcaddr
		,profcbupat
		,profccamat
		,profccmpname
		,profclurah
		,profcphone
		,profcprocy
		,profczipcd
		,prplaceofbirth
		,prreligion
		,prsex
		,prsmecustmodel
		,prstaylength
		,prtitle
		,prvipposition
		,quotationno
		,salesorderfuno
		,spbussinesseg
		,spbusaddr
		,spbusbupat
		,spbuscamat
		,spbuscmpname
		,spbuslurah
		,spbusprocy
		,spbuszipcd
		,spdateofbirth
		,spestablish
		,sphomaddr
		,sphombupat
		,sphomcamat
		,sphomlurah
		,sphomname
		,sphomprocy
		,sphomzipcd
		,spidnumber
		,spidtype
		,spincome
		,spjobposition
		,splegaddr
		,splegbupat
		,splegcamat
		,splegcmpname
		,spleglurah
		,splegprocy
		,splegzipcd
		,spname
		,spocupation
		,spofcaddr
		,spofcbupat
		,spofccamat
		,spofccmpname
		,spofclurah
		,spofcprocy
		,spofczipcd
		,spplaceofbirth
		,spphone
		,spreligion
		,spsex
		,spworkform
		,spyearemployeed
		,stnkid
		,stnkjob
		,stnkno
		,stnksex
		,stnkreligion
		,stnkaddr
		,stnkbupat
		,stnkcamat
		,stnklurah
		,stnkprocy
		,stnkzipcd
		,isvalidforacc
		,salesordertvcno
		,billingfutvcno
		,quotationtvcno
		,stnkcptgllahir
		,stnkcpstatuspernikahan
		,stnkcpemaiaddress
		,stnkcpkebangsaan
		,stnkcpstreet
		,stnkcpkelurahan
		,stnkcpkecamatan
		,stnkcpkota
		,stnkcppropinsi
		,stnkcpstnkkodepos
		,cptitle
		,iscorrespondenceselected
		,awotitle
		,stnkcptitle
		,opportunityid
		,wnacode
		,wnaname
		,salestypeid
		,proriginaladdress
		,crtype
		,crlegalnumber
		,purchaseorderno
		,approvalstatus
		,hargakendaraan
		,ap
		,subsidi
		,leasingpayment
		,leasingdate
		,namacustpo
		,insuranceproductid
		,isvalidinsuranceproduct
		,timestatus
		,rowstatus
		,createdby
		,lastmodifiedby
		,createdtime
		,lastmodifiedtime
		,uploaddate = getdate()
	from sales
	where rank = 1
)
select * from clean