version: 2

groups:
  - name: outbound_esvi
    owner:
      name: dbm

sources:
  - name: "{{ env_var('ENV_SCHEMA') + '_dl' }}"
    tables:
      - name: outbound_esvi_tms_prospect_intelix
      - name: outbound_esvi_tms_prospect_detail_intelix
      - name: outbound_esvi_tms_prospect_campaign_result_intelix
      - name: outbound_esvi_tms_prospect_history_contact_intelix
      - name: outbound_esvi_tms_prospect_time_frame_intelix
      - name: outbound_esvi_cc_master_category_intelix

models:
  - name: out_awo_esvi_report_prospect
