version: 2

groups:
  - name: outbound_adm
    owner:
      name: dbm

sources:
  - name: "{{ env_var('ENV_SCHEMA') + '_dl' }}"
    tables:
      - name: outbound_adm_tms_prospect_intelix
      - name: outbound_adm_tms_prospect_detail_intelix
      - name: outbound_adm_tms_prospect_campaign_result_intelix
      - name: outbound_adm_tms_prospect_history_contact_intelix
      - name: outbound_adm_tms_prospect_time_frame_intelix
      - name: outbound_adm_cc_master_category_intelix

models:
  - name: out_adm_recall_2025_noshow_report_prospect
  - name: out_adm_recall_2025_reminder_report_prospect
  - name: out_adm_recall_2025_report_prospect_timeframe
  - name: out_adm_recall_2025_report_prospect
  - name: out_dso_csi_v2_report_prospect_timeframe
  - name: out_dso_csi_v2_report_prospect
  - name: out_dso_ssi_v2_report_prospect_timeframe
  - name: out_dso_ssi_v2_report_prospect
