version: 2

groups:
  - name: ecentrix_alpha
    owner:
      name: dbm
  - name: outbound_mrsdso
    owner:
      name: dbm

sources:
  - name: "{{ env_var('ENV_SCHEMA') + '_dl' }}"
    tables:
      - name: ecentrix_alpha_ecentrix_session_log_intelix
      - name: ecentrix_alpha_ecentrix_reference_intelix

      - name: outbound_mrsdso_tms_prospect_intelix
      - name: outbound_mrsdso_tms_prospect_detail_intelix
      - name: outbound_mrsdso_tms_prospect_campaign_result_intelix
      - name: outbound_mrsdso_tms_prospect_history_contact_intelix
      - name: outbound_mrsdso_tms_prospect_time_frame_intelix
      - name: outbound_mrsdso_cc_master_category_intelix