version: 2

groups:
  - name: ecentrix_alpha
    owner:
      name: dbm

sources:
  - name: "{{ env_var('ENV_SCHEMA') + '_dl' }}"
    tables:
      - name: ecentrix_alpha_ecentrix_session_log_intelix
      - name: ecentrix_alpha_ecentrix_reference_intelix

models:
  - name: out_awo_esvi_report_telephony
  - name: out_clipan_duitcair_report_telephony
  - name: out_jmfi_mycash_report_telephony
