version: 2

groups:
  - name: outbound_mrsdso
    owner:
      name: dbm

sources:
  - name: "{{ env_var('ENV_SCHEMA') + '_dl' }}"
    tables:
      - name: outbound_mrsdso_tms_prospect_intelix
      - name: outbound_mrsdso_tms_prospect_detail_intelix
      - name: outbound_mrsdso_tms_prospect_campaign_result_intelix
      - name: outbound_mrsdso_tms_prospect_history_contact_intelix
      - name: outbound_mrsdso_tms_prospect_time_frame_intelix
      - name: outbound_mrsdso_cc_master_category_intelix

models:
  - name: out_dso_mrs_report_prospect_timeframe
  - name: out_dso_mrs_report_prospect
  - name: out_dso_revalidasi_report_prospect_timeframe
  - name: out_dso_revalidasi_report_prospect
  - name: out_tso_sweepcust_report_prospect
