AWO_CUSTOMER = "VW_AWOCustData_{so}{date}??????.txt"
AWO_CUSTOMER_ADDRESS = "VW_AWOCustAddressData_{so}{date}??????.txt"
AWO_CUSTOMER_ADDRESSUSAGE = "VW_AWOCustAddressUsageData_{so}{date}??????.txt"
AWO_CUSTOMER_CONTACT = "VW_AWOCustTelephoneData_{so}{date}??????.txt"
AWO_CUSTOMER_FAX = "VW_AWOCustFaxData_{so}{date}??????.txt"
AWO_CUSTOMER_MARKETINGATTRIBUTE = "VW_AWOCustMarketingAttribute_{so}{date}??????.txt"
AWO_CUSTOMER_SALESAREA = "VW_AWOCustSalesAreaData_{so}{date}??????.txt"

AWO_DETAIL_DEALER = "VW_AWOMasterDealer{date}??????.txt"

AWO_TRANSACTION_PKB = "vw_PKBAWO{date}_2.txt"
AWO_TRANSACTION_PKB_BILLING = "vw_billingserviceawo{date}.txt"
AWO_TRANSACTION_PKB_BOOKING = "vw_BookingAWO{date}.txt"
AWO_TRANSACTION_PKB_MATERIAL = "vw_PKBMaterial{date}.txt"
AWO_TRANSACTION_PKB_OPERATION = "vw_PKBOperation{date}.txt"
AWO_TRANSACTION_PKB_ORDERREQUEST = "vw_serviceorderrequest{date}.txt"
AWO_TRANSACTION_PKB_PARTNERDETAIL = "vw_pkbpartnerdetail{date}.txt"
AWO_TRANSACTION_PKB_SALESORDER = "vw_salesorderservice{date}.txt"

AWO_TRANSACTION_SALES = "VW_AWOBillingData{date}??????.txt"
AWO_TRANSACTION_SALES_V2 = "VW_AWOBillingDataV2.{date}.txt"
AWO_TRANSACTION_SALES_INVOICE = "VW_AWOTransInvoice{date}??????.txt"
AWO_TRANSACTION_SALES_PARTNERDETAIL = "VW_AWOPartnerDetail{date}??????.txt"
AWO_TRANSACTION_SALES_SALESORDER = "VW_AWOSalesOrderData{date}??????.txt"