version: 2

groups:
  - name: outbound_deskcolltaf
    owner:
      name: dbm

sources:
  - name: "{{ env_var('ENV_SCHEMA') + '_dl' }}"
    tables:
      - name: outbound_deskcolltaf_acs_call_history_daily_intelix
      - name: outbound_deskcolltaf_acs_call_history_detail_daily_intelix
      - name: outbound_deskcolltaf_acs_reference_intelix
      - name: outbound_deskcolltaf_acs_customer_profile_ext_intelix
      - name: outbound_deskcolltaf_acs_class_intelix
      - name: outbound_deskcolltaf_acs_payment_today_intelix

models:
  - name: out_taf_deskcoll_report_prospect
