version: 2

groups:
  - name: ecentrix_bravo
    owner:
      name: dbm

sources:
  - name: "{{ env_var('ENV_SCHEMA') + '_dl' }}"
    tables:
      - name: ecentrix_bravo_ecentrix_session_log_intelix
      - name: ecentrix_bravo_ecentrix_reference_intelix

models:
  - name: in_nasmoco_report_telephony
  - name: in_taf_report_telephony
  - name: in_tam_report_telephony
  - name: out_taf_cde_report_telephony
  - name: out_taf_teleacquisition_report_telephony
